### PR TITLE
Task/fix multimodule site

### PR DESCRIPTION
**Pull request by qurben**
Now creates a proper multimodule site.

Use `mvn site` to create a site, each submodule will have their own site. _Hyperlinks between sites don't work here._

Use `mvn site:stage` to stage the site to `target/staging`. This site is complete.

There will be regular updates of the site at http://geex.hup.blue/

### CODE REVIEW

**Comment by qurben** [comment]
Or for short: `mvn clean site site:stage`

The goal `site:stage` is very short and can only be run with the parent pom.

You can create sites for just one submodule.

**Comment by jboot** [comment]
mvn site::shipit:

**Comment by qurben** [comment]
Also fixes travis.

**Comment by jboot** [comment]
Oops :sheep:

**Pull request merged**
