### PR TITLE
Feature/shortcut view

### PR DESCRIPTION
**Pull request by qurben**
Press F1 to show the shortcut view.

Also took care of other shortcuts, they are managed in the menucontroller.

### CODE REVIEW

**Comment by jboot** [comment]
Cannot leave the window in any way. There is no close button and Esc is not working.

**Comment by jboot** [comment]
I could only leave the window with fn + Esc, strangely enough...

**Comment by jnieuwdorp** [comment]
Find bugs detects 2 bugs. 

```
Unread field: nl.tudelft.context.controller.MainController.menuController
Class nl.tudelft.context.newick.Tree defines non-transient non-serializable instance field root
```

Checkstyle: 2 unused imports & missing package-info file
PMD also has 3 issues

functionality is nice!

**Comment by Vennik** [comment]
Looks good. :shipit:

**Comment by jnieuwdorp** [comment]
Great :shipit: 
- FindBugs has one bug that will be fixed later 
- The shortcut overlay has one possibly undesired behavior atm where Esc doesn't close the overlay but moves up in the breadcrumb (might be fixed after merging)

**Pull request merged**
