### PR TITLE
Task/diagrams

### PR DESCRIPTION
**Pull request by qurben**
Chose [PlantUML](http://plantuml.sourceforge.net/) for UML diagrams. Also created a UML diagram of the entire project. Added the UML diagram to maven.

### CODE REVIEW

**Comment by qurben** [comment]
Please leave feedback about the relationships, some might be stricter or can be changed.
For the lazy:
UML Diagram

**Comment by Vennik** [comment]
The Graphviz dependency should be fixed.

**Comment by qurben** [comment]
If something is broken one should read README.md right? Or are there other places someone should look?

**Comment by Vennik** [comment]
:shipit:

**Pull request merged**
