### PR TITLE
Enhancement/filter sorting

### PR DESCRIPTION
**Pull request by qurben**
It is now possible to reorder filters by dragging them. Some more visual feedback could be added later.

### CODE REVIEW

**Comment by qurben** [comment]
Tests now work.

**Comment by jboot** [comment]
Nice job, but shortcuts `ctrl + arrow_up` and `ctrl + arrow_down` aren't working anymore. Either fix this issue, or remove the shortcuts.

**Comment by qurben** [comment]
Removed the hotkeys, it is currently not possible to properly see how many children are selected.

**Comment by jboot** [comment]
There are a few FindBugs errors that are caused by files you are working on. Could you please fix those?

**Comment by Vennik** [comment]
:shipit:

**Comment by jnieuwdorp** [comment]
There are a few checkstyle errors, please fix them before merging
There is also a bug reported by findbugs, but this might be fixed by merging. Please look into this

**Pull request merged**
