### PR TITLE
Feature/phylo styling

### PR DESCRIPTION
**Pull request by jboot**

### CODE REVIEW

**Comment by jnieuwdorp** [comment]
Looks nice! 
Find bugs: 0 
Checkstyle: Ok
PMD&CPD: 0 
Test coverage very good. 

There seems to be one little problem, it appears that sometimes 2 leafs are rendered in the same place.  (the highlighted leaf is below the other one, with only TKREF visible) 
Screenshot

And there's a TO DO statement on line 142 of maincontroller.java 

```
        // TODO: don't do this, for testing purposes only.
```

Please report back on this before shipping

**Comment by Vennik** [comment]
TODO will be removed when the workspace is implemented fully, has nothing to do with this pull request.

**Comment by jboot** [comment]
iwomm :) I never encountered this problem, @jnieuwdorp

**Comment by jboot** [comment]
Ok, you were right; resolved it!

**Comment by jnieuwdorp** [comment]
All good now. :shipit:

**Pull request merged**
