### PR TITLE
Task/diagram

### PR DESCRIPTION
**Pull request by qurben**
Update diagrams to reflect our current state.

### CODE REVIEW

**Comment by jnieuwdorp** [comment]
Looks good, from what point in time was the code that you used (for doccumentation, but I notice that annotations isn't included yet) :shipit:

**Comment by qurben** [comment]
20th of may, forgot to pull the most recent changes.

**Comment by jboot** [comment]
I can verify that; NewickLabel is also missing.

**Comment by Vennik** [comment]
An update is an update.

**Pull request merged**
