### PR TITLE
Enhancement/fix workspace

### PR DESCRIPTION
**Pull request by Vennik**
- Fixes null pointer on not selecting a workspace
- New submenu with recent workspaces.

### CODE REVIEW

**Comment by qurben** [comment]
Two PMD errors in `WelcomeController.java`
- Unnecessary use of fully qualified name 'Collectors.toList' due to existing import 'java.util.stream.Collectors' (119)
- Avoid empty catch blocks (158)

The second one might need some tweaking in PMD

**Comment by Vennik** [comment]
Fixed the PMD error that I introduced.

**Comment by qurben** [comment]
:shipit:

**Comment by jboot** [comment]
Can you make the menu more responsive? It doesn't update the list whenever a new workspace is introduced, or when the list needs to be reordered.

**Comment by qurben** [comment]
Good point, this was not needed in the initial design of the previous workspaces menu. It should however be very well possible.

**Comment by qurben** [comment]
Makes sense :shipit:

**Pull request merged**
