### PR TITLE
Feature/welcome screen

### PR DESCRIPTION
**Pull request by qurben**
Show a welcome screen.

Previous workspaces is a placeholder.

### CODE REVIEW

**Comment by Vennik** [comment]
Looks good. We should pull the overlay first though. :shipit:

**Comment by Vennik** [comment]
Looks good. We should pull the overlay first though. :shipit:

**Comment by Vennik** [comment]
Can you merge it into master, I'm not always sure about the intention of certain parts.

**Comment by jimhommes** [comment]
Looks good :shipit:

**Pull request merged**
