### PR TITLE
Feature/atcg percentage

### PR DESCRIPTION
**Pull request by jnieuwdorp**

### CODE REVIEW

**Comment by Vennik** [comment]
Try to store the length of the String as total in BaseCounter, and use that for calculating the the percentages. You are now running 5 times an O(n) on toString (values() on a HashMap is quite slow).

**Comment by Vennik** [comment]
:shipit:

**Comment by jnieuwdorp** [comment]
Hommes checked it, should be ready for merge

**Comment by jboot** [comment]
Looks awesome.

**Pull request merged**
