### PR TITLE
Feature/graph list

### PR DESCRIPTION
**Pull request by Vennik**
- Added a graph list that you can click to set the active graph filters.

### CODE REVIEW

**Comment by jimhommes** [comment]
Very nice, :shipit:

**Comment by jnieuwdorp** [comment]
When clicking through the first 3 items on the list I occasionally get an empty graph: 
image

Also, some text at the top of the list indicating what it does would be nice. 
I'll slightly adjust some text

**Comment by Vennik** [comment]
@jnieuwdorp Fixed that bug by merging with master.

**Comment by Vennik** [comment]
Fixed all the bugs.

**Comment by jnieuwdorp** [comment]
:shipit:

**Comment by qurben** [comment]
Awesome

**Pull request merged**
