### PR TITLE
Feature/show error

### PR DESCRIPTION
**Pull request by jimhommes**
Created a footer that displays text in the left bottom corner. You can test it by loading a faulty graph file. Please pay extra attention to the tests, I am unsure if I created these correctly.

### CODE REVIEW

**Comment by jnieuwdorp** [comment]
Maven report looks good. 

When loading a non-workspace folder, the footer shows "Ready" while the console gives an  IndexOutOfBounds

```
Exception in thread "JavaFX Application Thread" java.lang.IndexOutOfBoundsException: Index: 0, Size: 0
```

**Comment by jnieuwdorp** [comment]
Also when adding a folder without a .nwk file the program still displays "ready" while getting the IndexOutOfBounds in the console

**Comment by jnieuwdorp** [comment]
After loading a folder with only a .nwk file it does display "Error during loading tree" but it still opens the phylogenetic view (without a tree). Opening a valid workspace doesn't work anymore.

**Comment by jimhommes** [comment]
Fixed the problems above.

**Comment by jnieuwdorp** [comment]
Problems fixed, one problem arises, when selecting a folder without a .nwk file it displays the message: Succesfully loaded the workspace. But the main view remains empty. Every folder should have a .nwk file so this should result in an error.

**Comment by jnieuwdorp** [comment]
Works well now. Tests possibly could be better, but not sure how. coverage is more than 75% so :shipit:

**Comment by Vennik** [comment]
Please use the default controller.

**Comment by jnieuwdorp** [comment]
:shipit:

**Comment by jnieuwdorp** [comment]
:shipit:

**Comment by Vennik** [comment]
:shipit:

**Pull request merged**
