### PR TITLE
Added overlay on L press.

### LINKED ISSUE #126: 1. Make it possible to select parts from the phylogenetic tree.

### LINKED ISSUE #127: 2. Make it possible to see your selection (in old control panel space).

### LINKED ISSUE #128: 3. Create a button to load your selection (in old control panel space).

### PR DESCRIPTION
**Pull request by Vennik**
Fixes #126
Fixes #127
Fixes #128

### CODE REVIEW

**Comment by qurben** [comment]
In https://github.com/Vennik/contextproject/tree/feature/shortcut-view worden ook al allerlei dingen gedaan met een overlay. Misschien is het goed om voor beide dezelfde te gebruiken.

**Comment by Vennik** [comment]
It's not a real overlay. Just moving around the view in the background.

**Comment by Vennik** [comment]
There will be some other improvements.

**Comment by Vennik** [comment]
Now the breadcrumb doesn't throw away states.

**Comment by qurben** [comment]
I really like this. Would it be possible to emphasize the current location?

Just a simple _em_ or color change.

**Comment by Vennik** [comment]
Working on it.

**Comment by qurben** [comment]
:+1:

**Comment by jboot** [comment]
Looks nice. Could it be possible to load the already generated genome view when you're trying to load the same selection in the phylogenetic tree?

**Comment by Vennik** [comment]
Yes but not at this moment, put it in the backlog.

**Comment by jboot** [comment]
:shipit: then

**Pull request merged**
