### PR TITLE
Feature/workspace

### PR DESCRIPTION
**Pull request by qurben**
Created workspace.

Just choose a folder which contains at least a graph. The graph should load, you can switch between the first graph and the first newick in the workspace with the workspace menu at the top.

Navigating the workspace isn't yet implented. All the safety checks are not yet implemented too, also relies on the gui being implemented.

### CODE REVIEW

**Comment by jnieuwdorp** [comment]
Works, right now (because missing UI link) it's not possible to switch to phylogenetic tree visualization from workspace. Tests okay, PMD reports 3 errors, Find bugs has 6 bugs.

**Comment by qurben** [comment]
PMD errors aren't mine.

In the top menubar a new button should appear, to switch views.

**Comment by qurben** [comment]
FindBugs errors aren't mine either.

**Comment by Vennik** [comment]
Looks good. :shipit: 
We can work out the left sidebar as workspace with this (so the load buttons to the sidebar instead of the menu).

**Pull request merged**
